'use client';
import useSWR from 'swr';
import { useParams, useRouter } from 'next/navigation';
import Breadcrumbs from '@/components/Breadcrumbs';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import PatientForm, { type PatientFormValues } from '@/components/patients/PatientForm';
import { deletePatient, getHospitals, getPatient, getUsers, updatePatient } from '@/lib/api';

export default function PatientDetailPage(){const params=useParams<{id:string}>();const router=useRouter();const {data}=useSWR(params?.id?['/patients',params.id]:null,()=>getPatient(params.id));const {data:hospitalsRes,error:hospitalsError}=useSWR('/hospitals',()=>getHospitals());const {data:usersRes,error:usersError}=useSWR('/users',()=>getUsers());const p=data?.data;const a=p?.attributes??{};const hospitals=(hospitalsRes?.data??[]).map((h:any)=>({id:Number(h.id),name:h.attributes?.name??`Hospital ${h.id}`}));const users=(usersRes?.data??[]).map((u:any)=>({id:Number(u.id),name:u.attributes?.name??`User ${u.id}`,role:u.attributes?.role}));const initial:PatientFormValues={mrn:a.mrn??'',name:a.name??'',gender:(a.gender==='female'?'female':'male'),dob:a.dob??'',dos:a.dos??'',age:a.age!=null?String(a.age):'',height_cm:a.height_cm!=null?String(a.height_cm):'',weight_kg:a.weight_kg!=null?String(a.weight_kg):'',bsa:a.bsa!=null?String(a.bsa):'',blood_pressure:a.blood_pressure??'',diagnosis_brief:a.diagnosis_brief??'',referring_physician:a.referring_physician??'',hospital_id:String(p?.relationships?.hospital?.data?.id??''),user_id:String(p?.relationships?.user?.data?.id??'')};
return <div className='space-y-4'><Breadcrumbs items={[{label:'Dashboard',href:'/dashboard'},{label:'Patients',href:'/patients'},{label:a.name??'Patient'}]}/><Card><CardHeader><CardTitle>Edit Patient</CardTitle></CardHeader><CardContent>{!p?'Loading…':hospitalsError?<p className='text-sm text-destructive'>Unable to load hospitals for patient setup.</p>:usersError?<p className='text-sm text-destructive'>Unable to load users for patient setup.</p>:<PatientForm initialValues={initial} hospitals={hospitals} users={users} submitLabel='Save Patient' onSubmit={async(payload)=>{try{await updatePatient(params.id,payload);router.push('/patients');}catch(err:any){const msg=err?.response?await err.response.json().then((r:any)=>Object.values(r?.errors??{}).flat().join(' ')).catch(()=>null):null;throw new Error(msg||'Failed to update patient.');}}} onDelete={async()=>{if(!confirm('Delete this patient?'))return;await deletePatient(params.id);router.push('/patients');}}/>}</CardContent></Card></div>
}
